### ISSUE TITLE
Logs from experimental containers.

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#10]
Don't get an idea how to collect logs. Could you explain a little, please?

**Comment by schmunk42** [comment]
Ummm, `docker-compose logs -f --tail 100` for local development.
Or Yii2 debug panel - or audit module.

Or ... https://github.com/neam/docker-stack/tree/develop/stacks/schmunk42/elk-v2

What else do you need :)

**Comment by StalkAlex** [comment]
Thanks:)
