### ISSUE TITLE
Supervisord instead of Foreman

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#12]
How this can be solved if I want to use Supervisord inside container instead of current Foreman?

**Comment by StalkAlex** [comment]
Something like this? https://hub.docker.com/r/avarabyeu/alpine-supervisord/~/dockerfile/ But how can I turn off Foreman?

**Comment by schmunk42** [comment]
Hmm, they are pretty much doing the same job, aren't they?
I choose forego, because it's stable and lightweight.

**Comment by StalkAlex** [comment]
It's just matter of habit I think. We've been using supervisord for some time already. I didn't find some useful tricks like sending alerts by email, showing current statuses in cli, web access.

**Comment by StalkAlex** [comment]
So I found a way to install it.
