### ISSUE TITLE
Nginx gives error 413 for files uploads

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#13]
Those parameters need to be added to nginx.conf:
```bash
    # disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

    # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
    chunked_transfer_encoding on;
```
https://docs.docker.com/registry/recipes/nginx/

**Comment by StalkAlex** [comment]
And also this line 
```bash
    client_body_temp_path /tmp 1 2;
```
to avoid these kind of errors
```bash
2008/03/22 09:44:33 [crit] 18223#0: *642 open() "/usr/local/nginx/client_body_temp/0000000002" failed (13: Permission denied)
```

**Comment by schmunk42** [comment]
We thought this would be the fix: [sendfile off](https://github.com/dmstr/docker-php-yii2/blob/master/nginx/image-files/etc/nginx/nginx.conf#L36)

@handcode: Should we also add the custom temp path?

**Comment by handcode** [comment]
@schmunk42: I think this is another issue. 
The permission problem with /var/lib/nginx/tmp/client_body return 500 not 413

@StalkAlex 
disable upload limit completely isn't a good idea (IMHO)
how big was the file you try to upload?

**Comment by StalkAlex** [comment]
Yep, didn't mentioned that it's another issue - another error. 
Agree with you about this idea, just didn't find anything else. File was just 10 Mb or 5Mb.
