### ISSUE TITLE
Imagick hasn't been installed properly

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#14]
Here I found working way to install 
```bash
RUN set -x \
    && apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS imagemagick-dev libtool \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && apk add --no-cache --virtual .imagick-runtime-deps imagemagick \
    && apk del .phpize-deps
```
https://github.com/docker-library/php/issues/105

**Comment by schmunk42** [comment]
Is this about the missing PNG extension for ImageMagick? See also https://git.hrzg.de/dmstr/docker-php-yii2/builds/77762

I tried to build an image with the above code, but it failed. Were you able to build a PHP alpine locally?

CC: @handcode

**Comment by StalkAlex** [comment]
Not sure if missing png extension was a problem, but it was missing completely from phpinfo, it was not loaded at all. Then I tried to add it simply via `RUN docker-php-ext-install imagick` and `RUN docker-php-ext-enable imagick`, both commands said strangely name is unknown. We're using mPdf extension.

**Comment by bscheshirwork** [comment]
https://github.com/docker-library/php/issues/105#issuecomment-287466839

**Comment by StalkAlex** [comment]
@bscheshirwork I found it already, thanks. See question text.

**Comment by schmunk42** [comment]
Available in alpine build https://github.com/dmstr/docker-php-yii2/releases/tag/7.1-fpm-3.0-rc1
