### ISSUE TITLE
Session problem in 7.1 php-fpm-nginx-xdebug

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#15]
Php throws this error in session module `Could not gather sufficient random data`.
It looks there is a problem with alpine and/or latest php 7.1.2
https://github.com/docker-library/php/issues/376

I installed image about week ago, now It works fine, it uses older version of php 7.1.1, but new installation includes php 7.1.2 which throws above error. What would be correct way to rollback?

**Comment by schmunk42** [comment]
Hmmm, would have been the right thing to merge those :) https://github.com/dmstr/docker-php-yii2/pull/7 and https://github.com/dmstr/docker-php-yii2/pull/6

@handcode What do you think, should we manually update the patch versions in the base images? Eg. stay on 7.1.1 for now.

**Comment by StalkAlex** [comment]
Thanks for fix! What about idea to stay temporarily on php 7.1.1 and then return to 7.1.x after next release. As I understand this problem may be fixed.

**Comment by schmunk42** [comment]
Yes, will do so.

**Comment by StalkAlex** [comment]
Seems issue has been fixed in the last release. https://github.com/docker-library/php/issues/376#issuecomment-287708138
