### ISSUE TITLE
So... You could make the image smaller!

### ISSUE THREAD

**Issue by bscheshirwork** [dmstr/docker-php-yii2#16]
```
bscheshir/php                       fpm-alpine-4yii2-xdebug                651e888f98a2        20 hours ago        283 MB
dmstr/php-yii2                      latest-alpine                          6806630bf307        44 hours ago        381 MB
```
[:octocat:bscheshirwork/docker-php](https://github.com/bscheshirwork/docker-php)

**Comment by schmunk42** [comment]
Thank you for the feedback.

We're working on really small "offical" images here: https://github.com/yiisoft/yii2-docker/issues/7

It's planned that our images will use those as a base-image, input is very welcome.
