### ISSUE TITLE
Updating images

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#17]
Hello,
Are you planning further development? Will there be an image updates?

**Comment by schmunk42** [comment]
Yes, it's planned.

You may also send a PR with updated base-images, etc...

**Comment by schmunk42** [comment]
I tried to run builds from newer base images, but alpine fails, seems related to: https://github.com/webdevops/Dockerfile/issues/180 and https://github.com/krakjoe/apcu/issues/250

CC: @handcode

**Comment by schmunk42** [comment]
Updated 7.1 to 7.1.7 and there's also a 7.2.0beta3 now
