### ISSUE TITLE
Use stable mcrypt version when 7.2.0 is released

### ISSUE THREAD

**Issue by schmunk42** [dmstr/docker-php-yii2#18]
...and also think about removal of mcrypt for x.x-5.0 of this image - deprecated since a while (~10 years)

**Comment by StalkAlex** [comment]
Writing here due to not multiplying issues, is there any news on releasing images for PHP 7.2?

**Comment by schmunk42** [comment]
I can try to build 7.2 images here, but please note that Yii 2.0 Framework tests are currently failing, see https://travis-ci.org/yiisoft/yii2-docker/jobs/318080382 in `yiisoft/yii2-docker`.

Images built for `dmstr/docker-php-yii2` are only running requirement tests, but not framework tests.

**Comment by StalkAlex** [comment]
It means that they are not fully support it or just didn't adopt tests?

**Comment by StalkAlex** [comment]
Here's master build from yii2 repo for 7.2 https://travis-ci.org/yiisoft/yii2/jobs/318898681. There is no errors. Here's release run for last stable version https://travis-ci.org/yiisoft/yii2/jobs/301887690, it has problem with mime types only.

**Comment by schmunk42** [comment]
@StalkAlex You can give one of those a try:

```
7.2-fpm-4.0-alpha5-alpine-nginx
7.2-fpm-4.0-alpha5-nginx
7.2-fpm-4.0-alpha5-alpine
7.2-fpm-4.0-alpha5
```

**Comment by StalkAlex** [comment]
-xdebug version is lost...

**Comment by schmunk42** [comment]
Debug is available on the image, but not loaded, enabling it should also work by ENV-var.

**Comment by StalkAlex** [comment]
> Images built for dmstr/docker-php-yii2 are only running requirement tests, but not framework tests.

Hello, happy New Year! Is there any updates on this?

**Comment by schmunk42** [comment]
For the record: I just tried to use a newer mcrypt version with 7.2 but PHP is throwing errors, like:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/mcrypt.so (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/mcrypt.so: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/mcrypt.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/mcrypt.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

We'll keep mcrypt-1.0.0 as a legacy dependency in these images.

CC: @handcode
