### ISSUE TITLE
Update composer asset plugin in images

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#23]
Please release updated images due to bower url deprecation in fxp/composer-asset-plugin before 1.4.2.
Here's news http://www.yiiframework.com/forum/index.php/topic/75773-important-note-about-bower-and-the-asset-plugin/

**Comment by schmunk42** [comment]
I forgot to push this commit (to GitHub) a few days ago: https://github.com/dmstr/docker-php-yii2/commit/9f46dd5bfe83fc57dfb6688551df5d19b62d63e7

Should be fixed, let me know if there are issues.
