### ISSUE TITLE
Time zone problem

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#26]
I tried to change time zone inside a container and didn't get result that suppose to happen in vanilla alpine container. https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-341172222

But trying same on your image I get different result

```bash
phd root container 2406abc9ab16 /app
$ date
Thu Nov  2 04:28:10 UTC 2017
phd root container 2406abc9ab16 /app
$ apk add --no-cache tzdata
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://dl-3.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tzdata (2016d-r0)
Executing busybox-1.24.2-r13.trigger
OK: 209 MiB in 83 packages
phd root container 2406abc9ab16 /app
$ date
Thu Nov  2 04:28:29 UTC 2017
phd root container 2406abc9ab16 /app
$ export TZ='Asia/Almaty'
phd root container 2406abc9ab16 /app
$ date
Thu Nov  2 04:29:39 +06>-6 2017
phd root container 2406abc9ab16 /app
```
Difference in this thing `+06>-6`. In usual alpine I get changed time but here I get same UTC time but with this thing.

**Comment by schmunk42** [comment]
Please see https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-341316823

**Comment by StalkAlex** [comment]
I've seen it, thanks. It means there is a bug?

**Comment by schmunk42** [comment]
We've found many little quirky things with Alpine, this is like a "perfect example".

We are building 7.2 images (without asset plugin so far), which is based on Alpine 3.6, but 7.2 is not stable yet.

```
7.2-fpm-5.0-alpha4-alpine-nginx
131 MB
a month ago
7.2-fpm-5.0-alpha4-nginx
327 MB
a month ago
7.2-fpm-5.0-alpha4-alpine
128 MB
a month ago
7.2-fpm-5.0-alpha4
323 MB
a month ago
```

If you need this, maybe it's the best option to use our Debian images (all non `-alpine`).

**Comment by StalkAlex** [comment]
No, it's not an option for now. Thanks.
