### ISSUE TITLE
Only 7.0-fpm in docker hub

### ISSUE THREAD

**Issue by davidmpaz** [dmstr/docker-php-yii2#28]
Hi,

thanks for this images. I tried to pull version `7.1-fpm` as it was said to be available in README. But it is not pushed to hub.

Would be nice to have available `7.1-fpm` and/or `7.1-fpm-alpine`

Greetings,
David

**Comment by StalkAlex** [comment]
It's there, just check names. https://hub.docker.com/r/dmstr/php-yii2/tags/

**Comment by davidmpaz** [comment]
Oh!

thanks for answering and sorry that I reported this then.

Maybe would be good to make some reference to version numbers of tags. Lazy people like me :) can get confused, honestly i did not check tags, just read `7.1-fpm` on the readme and tried to pull it. I did miss the versions part like in: `7.1-fpm-3.2`

Cheers,
David

**Comment by schmunk42** [comment]
I am planning to make the `4.x` branch the master branch https://github.com/dmstr/docker-php-yii2/tree/release/4.x - the README is a more clearer here.
