### ISSUE TITLE
Support HTTP/2 in nginx image

### ISSUE THREAD

**Issue by darvids0n** [dmstr/docker-php-yii2#29]
In order for the Yii2 container to support we need to build against OpenSSL 1.0.2 or later. Current `latest-nginx` builds against 1.0.1t.

Ways this could be accomplished:

Debian
1. Add jessie-backports to sources.list, install nginx
1. FROM php:7.2-fpm, which uses stretch

Alpine
- Nginx in v3.3 and later branch *should* support although I have not confirmed

We should then also add `http2` to the listen directive for nginx config.

**Comment by schmunk42** [comment]
You should be able to add those lines to a custom `nginx.conf` (copy it from the image) to enable `http/2` - I tested this with alpine AFAIR. Please note that you also need to generate a certificate, any ideas how to handle that properly?

```
        listen 443 ssl http2;

        ssl_certificate /etc/nginx/ssl/default.crt;
        ssl_certificate_key /etc/nginx/ssl/default.key;
```

CC: @handcode
