### ISSUE TITLE
Question. Image updates

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#30]
Hi, guys, 

Is project alive? Is there any plans to update images? Current PHP 7.2 images are about 3 month old.

**Comment by schmunk42** [comment]
Thanks for your issue.

I've created a ` 7.2-fpm-4.0` tag which is based on latest PHP 7.2 - moreover there's now a nightly build for latest, based on the `release/4.x` branch.

**Comment by StalkAlex** [comment]
Thanks!

**Comment by StalkAlex** [comment]
What about update to Alpine 3.7 or there is no reason for that?

**Comment by schmunk42** [comment]
We actually don't use Alpine anymore, due to issues like https://github.com/yiisoft/yii2-docker/issues?q=is%3Aissue+label%3AAlpine+is%3Aclosed - ie. Yii framework tests do not pass on Alpine. 

But yeah, we still build Alpine images here, but actually we're just using the PHP Alpine flavour, so if they aren't on 3.7 we aren't also.

**Comment by StalkAlex** [comment]
3.7 versions has different naming on official PHP docker hub. You're extending `fpm-alpine`, those are 3.6 versions, 3.7 is `fpm-alpine3.7`.

**Comment by schmunk42** [comment]
I am sorry, but given the amount of time we've wasted for fixing highly esotheric Alpine issues, we won't extend support for it. I really do not recommend using it.

**Comment by StalkAlex** [comment]
Ok, thanks for advice. Should I move to yii2-docker extension or stay here just changing flavour?

**Comment by schmunk42** [comment]
In the mid-term we're also planning to move to `yii2-docker`, but we'll support this repo for at least mid 2019 - pick whatever works for you. The `yii2-docker` images are actually derived from this repo.

FYI: There's no `nginx` flavour for `yii2-docker`, https://github.com/yiisoft/yii2-docker/issues/12

**Comment by StalkAlex** [comment]
Great, thanks! I'll stay here for now then.  

It's very handy to have production-ready image with nginx+fpm, it's working in 90 percent of cases for yii apps imho.  Supporting nginx and fpm in a different containers is an overhead, your solution in this case works much better comparing to other variant from link above. At least it's good to have examples how to build nginx image or better have image itself.

**Comment by schmunk42** [comment]
Thank you for the kind words. If you want you can add your experience to the issue linked above, I also think it would facilitate development and deployment.
