### ISSUE TITLE
yii phpunit and codecept  with permission denied upon run on GCE

### ISSUE THREAD

**Issue by phdcoder** [dmstr/docker-php-yii2#31]
How to reproduce:  
1. Mount a VM with a container optimized image  in GCE   
2. start up a container with the alpine nginx 7.2 image 
3. exec a bash
4. try to run  "yii migrate" ( for example)  . results in permission denied. 

workaround:
use $php  ./file   
In my local environment(windows) this doesn't happen. Only on GCE.  composer works. 
Thanks for the great work !

**Comment by schmunk42** [comment]
Can you post more of the error output and maybe the current user in the container?

And could you try it with the Debian image, please.
We don't really support Alpine due to numerous issues.

I'd also recommend to use official images if possible: https://github.com/yiisoft/yii2-docker
