### ISSUE TITLE
Add PHP 7.3-rc

### ISSUE THREAD

**Issue by ivanmfan** [dmstr/docker-php-yii2#32]
Can you crate image PHP 7.3-rc please?

**Comment by schmunk42** [comment]
Created a branch - CI: https://git.hrzg.de/dmstr/docker-php-yii2/commit/fae57d74085746dd6e4383001996c3b2c3b608cb/pipelines

You should be able to build it on your own if you desperately need it.

**Comment by schmunk42** [comment]
PRs and/or improvements welcome.

https://git.hrzg.de/dmstr/docker-php-yii2/-/jobs/135900

**Comment by ivanmfan** [comment]
Install more newest apcu-5.1.3 -> apcu-5.1.14 +)

**Comment by ivanmfan** [comment]
For install xdebug
git checkout 52adff7539109db592d07d3f6c325f6ee2a7669f -> git checkout tags/2.7.0beta1

**Comment by ivanmfan** [comment]
For compilation memcached on alpine, you need use master branch, if it will be OK.
"PHP 7.3 patch has been pushed to master but not yet released on PECL"

**Comment by schmunk42** [comment]
Hmm, I can build that locally https://git.hrzg.de/dmstr/docker-php-yii2/-/jobs/136136 - I don't know why, could you give it a try?

But we're also thinking about dropping Alpine support anyway.
