### ISSUE TITLE
Setting timezone in php.ini

### ISSUE THREAD

**Issue by WeeSee** [dmstr/docker-php-yii2#34]
I'm using ```dmstr/php-yii2:7.2-fpm-4.6-alpine-nginx``` as base image. Really great!

How can I set the timezone in PHP ini-settings?

Can I do this in my docker-compose.yml file? 

Is there an ENV-Variable for the timezone?

**Comment by schmunk42** [comment]
There's no ENV var for that.

But you should be able to add an ini setting like so:

```
COPY timezone.ini /usr/local/etc/php/conf.d/timezone.ini
```

Note: Please be aware that we don't actively support Alpine PHP images, since we had many issues, especially with I18N, timezones and so on...
