### ISSUE TITLE
Package fxp/composer-asset-plugin at version ^1.4.1 has a PHP requirement incompatible with your PHP version

### ISSUE THREAD

**Issue by gs63875** [dmstr/docker-php-yii2#38]
Hi,
I am using dmstr/php-yii2:7.1-fpm-3.2-alpine-nginx docker image. facing below issue.

 Use composer self-update --rollback to return to version 1.5.2
 Changed current directory to /root/.composer
                                                                                                                                                      
   [InvalidArgumentException]                                                                                                                         
   Package fxp/composer-asset-plugin at version ^1.4.1 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  
                                                                                                                                                      
 require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]... 

The command '/bin/sh -c composer config -g github-oauth.github.com ${GITHUB_TOKEN}     && composer self-update     && composer global require "fxp/composer-asset-plugin:^1.4.1" 

How can i solve it.

tried : "fxp/composer-asset-plugin:dev-master"

**Comment by schmunk42** [comment]
Why do you roll-back to `1.5.2`?

The asset-plugin needs `1.6.0`. https://github.com/fxpio/composer-asset-plugin/blob/master/composer.json#L19

**Comment by gs63875** [comment]
I have this command in my Docker file 

RUN composer config -g github-oauth.github.com ${GITHUB_TOKEN} \
    && composer self-update \
    && composer global require "fxp/composer-asset-plugin:^1.4.1" --no-plugins

not doing anything related to roll-back.

**Comment by schmunk42** [comment]
Which version do you get from `composer self-update`?

You have to stay on 1.x

**Comment by gs63875** [comment]
yes. you are right!
comment the *composer self-update* looks working fine.
Thanks a lot!
