### ISSUE TITLE
composer 2 with PHP 7.4

### ISSUE THREAD

**Issue by WeeSee** [dmstr/docker-php-yii2#41]
Can we expect a version that supports PHP 7.4 and composer 2?

**Comment by schmunk42** [comment]
Please try this one: https://hub.docker.com/layers/dmstr/php-yii2/7.4-fpm-8.0-nginx/images/sha256-33fea9d9360f255a9ed0c207927b3efe9db23281151839855132bffc63a8964c?context=explore
