### ISSUE TITLE
Is "8.1-fpm-8.0-beta1-nginx" production ready?

### ISSUE THREAD

**Issue by raimon-segura** [dmstr/docker-php-yii2#42]
Hi!,

Thanks for this great docker image!!

Just I'm wondering if "8.1-fpm-8.0-beta1-nginx" is production ready or if anybody is using it in serious project... any hints?

Many thanks!

**Comment by schmunk42** [comment]
We're using it in dozens of production sites :+1: 

But those are also worth a look:
- https://github.com/yiisoft/yii-docker (can also be used for Yii2)
- https://github.com/yiisoft/yii2-docker
