### ISSUE TITLE
Change containers' config

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#8]
If, for example, one have need to change nginx and/or php-fpm own user from www-data to some other, how it supposed to be done correctly?

**Comment by schmunk42** [comment]
Example files:

![bildschirmfoto 2017-02-21 um 12 51 07](https://cloud.githubusercontent.com/assets/649031/23227774/55be3b4e-f93a-11e6-99ef-d220ac615c1d.png)

It's recommended to organize the files in the same folders as on the image. So you can run this to add your files...

```
COPY ./image-files /
```

with the above files, you'd replace `/root/Procfile`.

**Comment by StalkAlex** [comment]
I think this answer for another question :) but thanks, this is more suitable, now I just override one file by one.  

To current topic, problem is we're sharing code from devs' machines to vSphere VMs through NFS. It limits all file changes on guests to user who initiated file sharing, vagrant in our case. So before docker, php fpm run from vagrant user to avoid file permissions problem in assets creating, for example. It is known problem, now I see only one solution to use rsync, but it's more slower and less stable.

**Comment by StalkAlex** [comment]
So I've been managed to solve my specific problem. Solution is to add same host user to php container

```docker
  RUN adduser -D -u 1000 vagrant
```
and then run php-fpm from this user. It solves chmod permission denied problem for yii2.
