### ISSUE TITLE
Add beanstalk to own container extended from your image

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/docker-php-yii2#9]
As I uderstand I could extend your box and add everything I want so I just ask maybe you could give some hints how to add beanstalk service. I'm just new to Docker stuff.  I saw phd 5 repository, you've used Redis there.

**Comment by schmunk42** [comment]
Sorry, I've no experience with Beanstalk. You mean from AWS? What would it require?

In phd5 we're using a Redis container for caching.

**Comment by StalkAlex** [comment]
I meant Beanstalkd service. Now I am using ready image from hub. Before I find that image I thought to install it manually to container based on your images, Now problem's solved I guess.
